In [19]:
import pandas as pd

df = pd.read_csv('E:\\heart.csv')
df

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

In [20]:
x = df[['age','sex','cp','trtbps','chol','fbs','restecg','thalachh','exng','oldpeak','slp','caa','thall']].values
x.shape

(303, 13)

In [21]:
y = df['output'].values
y.shape

(303,)

In [22]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.30, random_state = 5)
x_test.shape

(91, 13)

In [23]:
from sklearn.tree import DecisionTreeClassifier

drugtree = DecisionTreeClassifier(criterion = 'entropy',max_depth = 4)

drugmodel = drugtree.fit(x_train,y_train)

y_predtree = drugmodel.predict(x_test)


In [24]:
print('testlot:',y_test.shape)
print('predlot:',y_predtree.shape)

testlot: (91,)
predlot: (91,)


In [25]:
from sklearn import metrics

print('accuracy score:',metrics.accuracy_score(y_test,y_predtree))

accuracy score: 0.6813186813186813


In [26]:
pd.crosstab(y_test,y_predtree)

col_0   0   1
row_0        
0      38   5
1      24  24

In [27]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predtree))

              precision    recall  f1-score   support

           0       0.61      0.88      0.72        43
           1       0.83      0.50      0.62        48

    accuracy                           0.68        91
   macro avg       0.72      0.69      0.67        91
weighted avg       0.73      0.68      0.67        91



In [28]:
drugmodel.predict_proba(x_test)

array([[0.        , 1.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 1.        ],
       [1.        , 0.        ],
       [0.5       , 0.5       ],
       [1.        , 0.        ],
       [0.5       , 0.5       ],
       [0.53846154, 0.46153846],
       [0.5       , 0.5       ],
       [1.        , 0.        ],
       [0.53846154, 0.46153846],
       [0.11538462, 0.88461538],
       [0.11538462, 0.88461538],
       [0.5       , 0.5       ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 1.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 1.        ],
       [1.        , 0.        ],
       [0.11538462, 0.88461538],
       [0.        , 1.        ],
       [0.5       , 0.5       ],
       [0.11538462, 0.88461538],
       [0.11538462, 0.88461538],
       [1.        , 0.        ],
       [0.

In [29]:
import numpy as np
y_predict_thr3 = np.where(drugmodel.predict_proba(x_test)[:,1]>0.2,1,0) # threshold is 0.3
y_predict_thr3

array([1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1])

In [30]:
def predict_threshold (drugmodel,x_test,thresholds):
    return np.where(drugmodel.predict_proba(x_test)[:,1]>thresholds,1,0)

In [31]:
from sklearn.metrics import confusion_matrix

In [32]:
for thr in np.arange(0,1.1,0.1):
    y_predict = predict_threshold(drugmodel,x_test,thr)
    print('Thresholds:',thr)
    print(confusion_matrix(y_test,y_predict))

Thresholds: 0.0
[[33 10]
 [ 1 47]]
Thresholds: 0.1
[[33 10]
 [ 1 47]]
Thresholds: 0.2
[[33 10]
 [ 1 47]]
Thresholds: 0.30000000000000004
[[33 10]
 [ 1 47]]
Thresholds: 0.4
[[33 10]
 [ 1 47]]
Thresholds: 0.5
[[38  5]
 [24 24]]
Thresholds: 0.6000000000000001
[[38  5]
 [24 24]]
Thresholds: 0.7000000000000001
[[38  5]
 [24 24]]
Thresholds: 0.8
[[38  5]
 [24 24]]
Thresholds: 0.9
[[41  2]
 [31 17]]
Thresholds: 1.0
[[43  0]
 [48  0]]


In [33]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predict_thr3))

              precision    recall  f1-score   support

           0       0.97      0.77      0.86        43
           1       0.82      0.98      0.90        48

    accuracy                           0.88        91
   macro avg       0.90      0.87      0.88        91
weighted avg       0.89      0.88      0.88        91



In [34]:
pd.crosstab(y_test,y_predict_thr3)

col_0   0   1
row_0        
0      33  10
1       1  47