In [509]:
import pandas as pd


df0 = pd.read_csv('E:\\healthcare-dataset-stroke-data.csv') 
df0.head()

id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
1  51676  Female  61.0             0              0          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
1  Self-employed          Rural             202.21   NaN     never smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1

In [510]:
df0.columns

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

In [511]:
# converts categorical data into numerical data
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [512]:
df0['smoking_status_code'],df0['ever_married_code'],df0['work_type_code'],df0['Residence_type_code'],df0['Gender_code'] = le.fit_transform(df0.smoking_status),le.fit_transform(df0.ever_married),le.fit_transform(df0.work_type),le.fit_transform(df0.Residence_type),le.fit_transform(df0.gender)
df0

id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes   
1     51676  Female  61.0             0              0          Yes   
2     31112    Male  80.0             0              1          Yes   
3     60182  Female  49.0             0              0          Yes   
4      1665  Female  79.0             1              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5105  18234  Female  80.0             1              0          Yes   
5106  44873  Female  81.0             0              0          Yes   
5107  19723  Female  35.0             0              0          Yes   
5108  37544    Male  51.0             0              0          Yes   
5109  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
1     Self-employed          Rural             202.21   NaN     never smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
...             ...            ...                ...   ...              ...   
5105        Private          Urban              83.75   NaN     never smoked   
5106  Self-employed          Urban             125.20  40.0     never smoked   
5107  Self-employed          Rural              82.99  30.6     never smoked   
5108        Private          Rural             166.29  25.6  formerly smoked   
5109       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  smoking_status_code  ever_married_code  work_type_code  \
0          1                    1                  1               2   
1          1                    2                  1               3   
2          1                    2                  1               2   
3          1                    3                  1               2   
4          1                    2                  1               3   
...      ...                  ...                ...             ...   
5105       0                    2                  1               2   
5106       0                    2                  1               3   
5107       0                    2                  1               3   
5108       0                    1                  1               2   
5109       0                    0                  1               0   

      Residence_type_code  Gender_code  
0                       1            1  
1                       0            0  
2                       0            1  
3                       1            0  
4                       0            0  
...                   ...          ...  
5105                    1            0  
5106                    1            0  
5107                    0            0  
5108                    0            1  
5109                    1            0  

[5110 rows x 17 columns]

In [513]:
df1 = pd.DataFrame()

df1['hypertension'],df1['heart_disease'],df1['avg_glucose_level'],df1['bmi'],df1['smoking_status_code'],df1['ever_married_code'],df1['work_type_code'],df1['Residence_type_code'],df1['Gender_code'],df1['stroke'] = df0['hypertension'],df0['heart_disease'],df0['avg_glucose_level'],df0['bmi'],df0['smoking_status_code'],df0['ever_married_code'],df0['work_type_code'],df0['Residence_type_code'],df0['Gender_code'],df0['stroke'] 

In [514]:
import numpy as np

mean = df1['bmi'].mean()
df1['bmi'].replace(np.NaN,mean, inplace = True)
df1

hypertension  heart_disease  avg_glucose_level        bmi  \
0                0              1             228.69  36.600000   
1                0              0             202.21  28.893237   
2                0              1             105.92  32.500000   
3                0              0             171.23  34.400000   
4                1              0             174.12  24.000000   
...            ...            ...                ...        ...   
5105             1              0              83.75  28.893237   
5106             0              0             125.20  40.000000   
5107             0              0              82.99  30.600000   
5108             0              0             166.29  25.600000   
5109             0              0              85.28  26.200000   

      smoking_status_code  ever_married_code  work_type_code  \
0                       1                  1               2   
1                       2                  1               3   
2                       2                  1               2   
3                       3                  1               2   
4                       2                  1               3   
...                   ...                ...             ...   
5105                    2                  1               2   
5106                    2                  1               3   
5107                    2                  1               3   
5108                    1                  1               2   
5109                    0                  1               0   

      Residence_type_code  Gender_code  stroke  
0                       1            1       1  
1                       0            0       1  
2                       0            1       1  
3                       1            0       1  
4                       0            0       1  
...                   ...          ...     ...  
5105                    1            0       0  
5106                    1            0       0  
5107                    0            0       0  
5108                    0            1       0  
5109                    1            0       0  

[5110 rows x 10 columns]

In [515]:
x = df1[['hypertension','heart_disease','avg_glucose_level','bmi','smoking_status_code','ever_married_code','work_type_code','Residence_type_code','Gender_code']].values
x[0:5]

array([[  0.        ,   1.        , 228.69      ,  36.6       ,
          1.        ,   1.        ,   2.        ,   1.        ,
          1.        ],
       [  0.        ,   0.        , 202.21      ,  28.89323691,
          2.        ,   1.        ,   3.        ,   0.        ,
          0.        ],
       [  0.        ,   1.        , 105.92      ,  32.5       ,
          2.        ,   1.        ,   2.        ,   0.        ,
          1.        ],
       [  0.        ,   0.        , 171.23      ,  34.4       ,
          3.        ,   1.        ,   2.        ,   1.        ,
          0.        ],
       [  1.        ,   0.        , 174.12      ,  24.        ,
          2.        ,   1.        ,   3.        ,   0.        ,
          0.        ]])

In [516]:
df1.shape

(5110, 10)

In [517]:
df1.isnull().sum()

hypertension           0
heart_disease          0
avg_glucose_level      0
bmi                    0
smoking_status_code    0
ever_married_code      0
work_type_code         0
Residence_type_code    0
Gender_code            0
stroke                 0
dtype: int64

In [518]:
y = df1['stroke'].values
y[0:5]

array([1, 1, 1, 1, 1], dtype=int64)

In [519]:
df1['stroke'].value_counts()

0    4861
1     249
Name: stroke, dtype: int64

In [520]:
#Normalize the data, this gives zero to mean data and unit variance

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scale = scaler.fit(x).transform(x)
x[0:5]

array([[  0.        ,   1.        , 228.69      ,  36.6       ,
          1.        ,   1.        ,   2.        ,   1.        ,
          1.        ],
       [  0.        ,   0.        , 202.21      ,  28.89323691,
          2.        ,   1.        ,   3.        ,   0.        ,
          0.        ],
       [  0.        ,   1.        , 105.92      ,  32.5       ,
          2.        ,   1.        ,   2.        ,   0.        ,
          1.        ],
       [  0.        ,   0.        , 171.23      ,  34.4       ,
          3.        ,   1.        ,   2.        ,   1.        ,
          0.        ],
       [  1.        ,   0.        , 174.12      ,  24.        ,
          2.        ,   1.        ,   3.        ,   0.        ,
          0.        ]])

In [521]:
#split data in train and test datasets
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.30,random_state=4)
x_train.shape

(3577, 9)

In [522]:
#perform the classification using KNN
#Import the KNN library

from sklearn.neighbors import KNeighborsClassifier

#Train the data on the KNN algorithm

k = 5

neigh = KNeighborsClassifier(n_neighbors = k).fit(x_train,y_train)

#Predicting with KNN

yhat = neigh.predict(x_test)
yhat

#accuracy evaluation

from sklearn import metrics

print('accuracy_score for train set:',metrics.accuracy_score(y_train, neigh.predict(x_train)))
print('accuracy_score for test set:', metrics.accuracy_score(y_test,yhat))



accuracy_score for train set: 0.9493989376572547
accuracy_score for test set: 0.9549902152641878


In [523]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,yhat)

array([[1463,    2],
       [  67,    1]], dtype=int64)

In [524]:
pd.crosstab(y_test,yhat)

col_0     0  1
row_0         
0      1463  2
1        67  1

In [525]:
y_test.shape

(1533,)

In [526]:
from sklearn.metrics import classification_report
print(classification_report(y_test,yhat))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98      1465
           1       0.33      0.01      0.03        68

    accuracy                           0.95      1533
   macro avg       0.64      0.51      0.50      1533
weighted avg       0.93      0.95      0.93      1533



In [527]:
neigh.predict_proba(x_test)[:,1]

array([0., 0., 0., ..., 0., 0., 0.])

In [528]:
import numpy as np

y_predict_thr3 = np.where(neigh.predict_proba(x_test)[:,1]>0.3,1,0) # threshold is 0.3
y_predict_thr4 = np.where(neigh.predict_proba(x_test)[:,1]>0.4,1,0) # threshold is 0.4

In [529]:
def predict_threshold (neigh,x_test,thresholds):
    return np.where(neigh.predict_proba(x_test)[:,1]>thresholds,1,0)

In [530]:
for thr in np.arange(0,1.0,0.1):
    y_predict = predict_threshold(neigh,x_test,thr)
    print('Thresholds:',thr)
    print(confusion_matrix(y_test,y_predict))

Thresholds: 0.0
[[1138  327]
 [  44   24]]
Thresholds: 0.1
[[1138  327]
 [  44   24]]
Thresholds: 0.2
[[1430   35]
 [  64    4]]
Thresholds: 0.30000000000000004
[[1430   35]
 [  64    4]]
Thresholds: 0.4
[[1463    2]
 [  67    1]]
Thresholds: 0.5
[[1463    2]
 [  67    1]]
Thresholds: 0.6000000000000001
[[1465    0]
 [  68    0]]
Thresholds: 0.7000000000000001
[[1465    0]
 [  68    0]]
Thresholds: 0.8
[[1465    0]
 [  68    0]]
Thresholds: 0.9
[[1465    0]
 [  68    0]]
